[package]
name = "dotty"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]
members = [
    "crates/dotty-tasty",
    "crates/dotty-classfile",
    "crates/dotty-lexer",
    "crates/dotty-core",
    "crates/dotty-classloader",
    "crates/dotty-tasty-unpickler",
    "crates/dotty-parser",
    "crates/dotty-namer",
    "crates/dotty-typer",
    "tools/parser-smoke-dump",
    "tools/parser-corpus-report",
]
resolver = "3"

[profile.test]
opt-level = 1

[dependencies]
dotty-tasty = { path = "crates/dotty-tasty" }
dotty-classfile = { path = "crates/dotty-classfile" }
dotty-core = { path = "crates/dotty-core" }
dotty-classloader = { path = "crates/dotty-classloader" }
dotty-tasty-unpickler = { path = "crates/dotty-tasty-unpickler" }
dotty-parser = { path = "crates/dotty-parser" }
dotty-namer = { path = "crates/dotty-namer" }
dotty-typer = { path = "crates/dotty-typer" }
