[package]
name = "dotty"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]
members = [
    "crates/dotty-tasty",
    "crates/dotty-classfile",
    "crates/dotty-source",
    "crates/dotty-diagnostics",
    "crates/dotty-token",
    "crates/dotty-lexer",
    "crates/dotty-core",
]
resolver = "3"

[profile.test]
opt-level = 1

[dependencies]
dotty-tasty = { path = "crates/dotty-tasty" }
dotty-classfile = { path = "crates/dotty-classfile" }
dotty-core = { path = "crates/dotty-core" }
