[package]
name = "dotty-typer"
version = "0.1.0"
edition = "2024"

[dependencies]
dotty-core = { path = "../dotty-core" }
dotty-namer = { path = "../dotty-namer" }

[dev-dependencies]
dotty-lexer = { path = "../dotty-lexer" }
dotty-parser = { path = "../dotty-parser" }
dotty-tasty = { path = "../dotty-tasty" }
dotty-tasty-unpickler = { path = "../dotty-tasty-unpickler" }
